// Entire integration plugin for OpenCode.
// This file is auto-generated by `entire enable` — do not edit manually.
// It hooks into OpenCode's plugin system to notify Entire of session lifecycle events.

import { execSync } from "child_process";

interface PluginContext {
  $: any;
  client: any;
  project: any;
  directory: string;
  worktree: string;
}

interface HookPayload {
  session_id: string;
  session_ref: string;
  timestamp: string;
  transcript_path: string;
  tool_name?: string;
  tool_use_id?: string;
  tool_input?: Record<string, unknown>;
  tool_response?: Record<string, unknown>;
  subagent_transcript_path?: string;
}

function callEntire(verb: string, payload: HookPayload): void {
  try {
    const input = JSON.stringify(payload);
    execSync(`entire hooks opencode ${verb}`, {
      input,
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30_000,
    });
  } catch {
    // Silently ignore errors — hooks must not block the agent
  }
}

function getTranscriptPath(ctx: PluginContext, sessionId: string): string {
  return `${ctx.directory}/.opencode/sessions/${sessionId}.jsonl`;
}

export default function plugin(ctx: PluginContext) {
  const { $ } = ctx;

  $.on("session.created", (event: { sessionId: string }) => {
    const payload: HookPayload = {
      session_id: event.sessionId,
      session_ref: event.sessionId,
      timestamp: new Date().toISOString(),
      transcript_path: getTranscriptPath(ctx, event.sessionId),
    };
    callEntire("session-start", payload);
  });

  $.on("session.idle", (event: { sessionId: string }) => {
    const payload: HookPayload = {
      session_id: event.sessionId,
      session_ref: event.sessionId,
      timestamp: new Date().toISOString(),
      transcript_path: getTranscriptPath(ctx, event.sessionId),
    };
    callEntire("stop", payload);
  });

  $.on(
    "tool.execute.before",
    (event: { sessionId: string; toolName: string; toolUseId: string; input: Record<string, unknown> }) => {
      if (event.toolName !== "Task") return;
      const payload: HookPayload = {
        session_id: event.sessionId,
        session_ref: event.sessionId,
        timestamp: new Date().toISOString(),
        transcript_path: getTranscriptPath(ctx, event.sessionId),
        tool_name: event.toolName,
        tool_use_id: event.toolUseId,
        tool_input: event.input,
      };
      callEntire("task-start", payload);
    },
  );

  $.on(
    "tool.execute.after",
    (event: {
      sessionId: string;
      toolName: string;
      toolUseId: string;
      input: Record<string, unknown>;
      output: Record<string, unknown>;
    }) => {
      if (event.toolName !== "Task") return;
      const payload: HookPayload = {
        session_id: event.sessionId,
        session_ref: event.sessionId,
        timestamp: new Date().toISOString(),
        transcript_path: getTranscriptPath(ctx, event.sessionId),
        tool_name: event.toolName,
        tool_use_id: event.toolUseId,
        tool_input: event.input,
        tool_response: event.output,
      };
      callEntire("task-complete", payload);
    },
  );
}
